apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-gen-agent.fullname" . }}-config
  labels:
    {{- include "image-gen-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "image-gen-agent.configContent" . | nindent 4 }}
