apiVersion: v1
kind: Service
metadata:
  name: insurance-expert
  namespace: insurance-expert
  labels:
    app: insurance-expert
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: insurance-expert

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-expert-headless
  namespace: insurance-expert
  labels:
    app: insurance-expert
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: insurance-expert
