apiVersion: v1
kind: Service
metadata:
  name: image-gen-agent
  namespace: image-gen-agent
  labels:
    app.kubernetes.io/name: image-gen-agent
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: image-gen-agent
    app.kubernetes.io/component: server
