// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: memory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreRequest 存储请求
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Message       *MessageInput          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options       *StoreOptions          `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StoreRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StoreRequest) GetMessage() *MessageInput {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StoreRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreRequest) GetOptions() *StoreOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// MessageInput 消息输入
type MessageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	TopicId       string                 `protobuf:"bytes,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInput) Reset() {
	*x = MessageInput{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInput) ProtoMessage() {}

func (x *MessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInput.ProtoReflect.Descriptor instead.
func (*MessageInput) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MessageInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInput) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *MessageInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StoreOptions 存储选项
type StoreOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExtractEntities   bool                   `protobuf:"varint,1,opt,name=extract_entities,json=extractEntities,proto3" json:"extract_entities,omitempty"`
	GenerateEmbedding bool                   `protobuf:"varint,2,opt,name=generate_embedding,json=generateEmbedding,proto3" json:"generate_embedding,omitempty"`
	Importance        float64                `protobuf:"fixed64,3,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreOptions) Reset() {
	*x = StoreOptions{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOptions) ProtoMessage() {}

func (x *StoreOptions) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOptions.ProtoReflect.Descriptor instead.
func (*StoreOptions) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreOptions) GetExtractEntities() bool {
	if x != nil {
		return x.ExtractEntities
	}
	return false
}

func (x *StoreOptions) GetGenerateEmbedding() bool {
	if x != nil {
		return x.GenerateEmbedding
	}
	return false
}

func (x *StoreOptions) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

// StoreResponse 存储响应
type StoreResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageId         string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Tier              string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	TokenCount        int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	EntitiesExtracted []string               `protobuf:"bytes,4,rep,name=entities_extracted,json=entitiesExtracted,proto3" json:"entities_extracted,omitempty"`
	ArchiveTriggered  bool                   `protobuf:"varint,5,opt,name=archive_triggered,json=archiveTriggered,proto3" json:"archive_triggered,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{3}
}

func (x *StoreResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StoreResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *StoreResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *StoreResponse) GetEntitiesExtracted() []string {
	if x != nil {
		return x.EntitiesExtracted
	}
	return nil
}

func (x *StoreResponse) GetArchiveTriggered() bool {
	if x != nil {
		return x.ArchiveTriggered
	}
	return false
}

// RetrieveRequest 检索请求
type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Options       *RetrieveOptions       `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetOptions() *RetrieveOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// RetrieveOptions 检索选项
type RetrieveOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenBudget     int32                  `protobuf:"varint,1,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	TopicId         string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TimeRange       *TimeRange             `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Filters         map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IncludeSummary  bool                   `protobuf:"varint,5,opt,name=include_summary,json=includeSummary,proto3" json:"include_summary,omitempty"`
	IncludeEntities bool                   `protobuf:"varint,6,opt,name=include_entities,json=includeEntities,proto3" json:"include_entities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveOptions) Reset() {
	*x = RetrieveOptions{}
	mi := &file_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveOptions) ProtoMessage() {}

func (x *RetrieveOptions) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveOptions.ProtoReflect.Descriptor instead.
func (*RetrieveOptions) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveOptions) GetTokenBudget() int32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *RetrieveOptions) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *RetrieveOptions) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *RetrieveOptions) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *RetrieveOptions) GetIncludeSummary() bool {
	if x != nil {
		return x.IncludeSummary
	}
	return false
}

func (x *RetrieveOptions) GetIncludeEntities() bool {
	if x != nil {
		return x.IncludeEntities
	}
	return false
}

// TimeRange 时间范围
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // Unix timestamp
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{6}
}

func (x *TimeRange) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeRange) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

// RetrieveResponse 检索响应
type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       []*ContextItem         `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Entities      []*EntityInfo          `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	SearchStats   *SearchStats           `protobuf:"bytes,5,opt,name=search_stats,json=searchStats,proto3" json:"search_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveResponse) GetContext() []*ContextItem {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RetrieveResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RetrieveResponse) GetEntities() []*EntityInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RetrieveResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *RetrieveResponse) GetSearchStats() *SearchStats {
	if x != nil {
		return x.SearchStats
	}
	return nil
}

// ContextItem 上下文项
type ContextItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,5,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Tier           string                 `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContextItem) Reset() {
	*x = ContextItem{}
	mi := &file_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextItem) ProtoMessage() {}

func (x *ContextItem) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextItem.ProtoReflect.Descriptor instead.
func (*ContextItem) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{8}
}

func (x *ContextItem) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ContextItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ContextItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ContextItem) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *ContextItem) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

// EntityInfo 实体信息
type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Mentions      int32                  `protobuf:"varint,3,opt,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{9}
}

func (x *EntityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityInfo) GetMentions() int32 {
	if x != nil {
		return x.Mentions
	}
	return 0
}

// SearchStats 搜索统计
type SearchStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	L1Hits          int32                  `protobuf:"varint,1,opt,name=l1_hits,json=l1Hits,proto3" json:"l1_hits,omitempty"`
	L2Hits          int32                  `protobuf:"varint,2,opt,name=l2_hits,json=l2Hits,proto3" json:"l2_hits,omitempty"`
	L3Hits          int32                  `protobuf:"varint,3,opt,name=l3_hits,json=l3Hits,proto3" json:"l3_hits,omitempty"`
	SearchLatencyMs int64                  `protobuf:"varint,4,opt,name=search_latency_ms,json=searchLatencyMs,proto3" json:"search_latency_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchStats) Reset() {
	*x = SearchStats{}
	mi := &file_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStats) ProtoMessage() {}

func (x *SearchStats) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStats.ProtoReflect.Descriptor instead.
func (*SearchStats) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{10}
}

func (x *SearchStats) GetL1Hits() int32 {
	if x != nil {
		return x.L1Hits
	}
	return 0
}

func (x *SearchStats) GetL2Hits() int32 {
	if x != nil {
		return x.L2Hits
	}
	return 0
}

func (x *SearchStats) GetL3Hits() int32 {
	if x != nil {
		return x.L3Hits
	}
	return 0
}

func (x *SearchStats) GetSearchLatencyMs() int64 {
	if x != nil {
		return x.SearchLatencyMs
	}
	return 0
}

// BatchStoreRequest 批量存储请求
type BatchStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Messages      []*MessageInput        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Options       *BatchStoreOptions     `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreRequest) Reset() {
	*x = BatchStoreRequest{}
	mi := &file_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreRequest) ProtoMessage() {}

func (x *BatchStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreRequest.ProtoReflect.Descriptor instead.
func (*BatchStoreRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{11}
}

func (x *BatchStoreRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchStoreRequest) GetMessages() []*MessageInput {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BatchStoreRequest) GetOptions() *BatchStoreOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// BatchStoreOptions 批量存储选项
type BatchStoreOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PreserveOrder      bool                   `protobuf:"varint,1,opt,name=preserve_order,json=preserveOrder,proto3" json:"preserve_order,omitempty"`
	ParallelProcessing bool                   `protobuf:"varint,2,opt,name=parallel_processing,json=parallelProcessing,proto3" json:"parallel_processing,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchStoreOptions) Reset() {
	*x = BatchStoreOptions{}
	mi := &file_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreOptions) ProtoMessage() {}

func (x *BatchStoreOptions) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreOptions.ProtoReflect.Descriptor instead.
func (*BatchStoreOptions) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{12}
}

func (x *BatchStoreOptions) GetPreserveOrder() bool {
	if x != nil {
		return x.PreserveOrder
	}
	return false
}

func (x *BatchStoreOptions) GetParallelProcessing() bool {
	if x != nil {
		return x.ParallelProcessing
	}
	return false
}

// BatchStoreResponse 批量存储响应
type BatchStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*StoreResponse       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreResponse) Reset() {
	*x = BatchStoreResponse{}
	mi := &file_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreResponse) ProtoMessage() {}

func (x *BatchStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreResponse.ProtoReflect.Descriptor instead.
func (*BatchStoreResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{13}
}

func (x *BatchStoreResponse) GetResults() []*StoreResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchStoreResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchStoreResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchStoreResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// BatchRetrieveRequest 批量检索请求
type BatchRetrieveRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Requests      []*SingleRetrieveRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Options       *BatchRetrieveOptions    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveRequest) Reset() {
	*x = BatchRetrieveRequest{}
	mi := &file_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveRequest) ProtoMessage() {}

func (x *BatchRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveRequest.ProtoReflect.Descriptor instead.
func (*BatchRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{14}
}

func (x *BatchRetrieveRequest) GetRequests() []*SingleRetrieveRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchRetrieveRequest) GetOptions() *BatchRetrieveOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SingleRetrieveRequest 单个检索请求
type SingleRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleRetrieveRequest) Reset() {
	*x = SingleRetrieveRequest{}
	mi := &file_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRetrieveRequest) ProtoMessage() {}

func (x *SingleRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRetrieveRequest.ProtoReflect.Descriptor instead.
func (*SingleRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{15}
}

func (x *SingleRetrieveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SingleRetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// BatchRetrieveOptions 批量检索选项
type BatchRetrieveOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parallel      bool                   `protobuf:"varint,1,opt,name=parallel,proto3" json:"parallel,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveOptions) Reset() {
	*x = BatchRetrieveOptions{}
	mi := &file_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveOptions) ProtoMessage() {}

func (x *BatchRetrieveOptions) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveOptions.ProtoReflect.Descriptor instead.
func (*BatchRetrieveOptions) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{16}
}

func (x *BatchRetrieveOptions) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

func (x *BatchRetrieveOptions) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// BatchRetrieveResponse 批量检索响应
type BatchRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RetrieveResponse    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveResponse) Reset() {
	*x = BatchRetrieveResponse{}
	mi := &file_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveResponse) ProtoMessage() {}

func (x *BatchRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveResponse.ProtoReflect.Descriptor instead.
func (*BatchRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{17}
}

func (x *BatchRetrieveResponse) GetResults() []*RetrieveResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetSessionRequest 获取会话请求
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{18}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionInfo 会话信息
type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageCount   int32                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TokenCount     int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	TopicCount     int32                  `protobuf:"varint,4,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	CurrentTopicId string                 `protobuf:"bytes,5,opt,name=current_topic_id,json=currentTopicId,proto3" json:"current_topic_id,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt   int64                  `protobuf:"varint,7,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{19}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionInfo) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *SessionInfo) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *SessionInfo) GetCurrentTopicId() string {
	if x != nil {
		return x.CurrentTopicId
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

// DeleteSessionRequest 删除会话请求
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DeleteSessionResponse 删除会话响应
type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteSessionResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// SwitchTopicRequest 切换主题请求
type SwitchTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NewTopic      string                 `protobuf:"bytes,2,opt,name=new_topic,json=newTopic,proto3" json:"new_topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTopicRequest) Reset() {
	*x = SwitchTopicRequest{}
	mi := &file_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTopicRequest) ProtoMessage() {}

func (x *SwitchTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTopicRequest.ProtoReflect.Descriptor instead.
func (*SwitchTopicRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{22}
}

func (x *SwitchTopicRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SwitchTopicRequest) GetNewTopic() string {
	if x != nil {
		return x.NewTopic
	}
	return ""
}

// SwitchTopicResponse 切换主题响应
type SwitchTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	TopicTitle    string                 `protobuf:"bytes,2,opt,name=topic_title,json=topicTitle,proto3" json:"topic_title,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TokenCount    int32                  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTopicResponse) Reset() {
	*x = SwitchTopicResponse{}
	mi := &file_memory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTopicResponse) ProtoMessage() {}

func (x *SwitchTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTopicResponse.ProtoReflect.Descriptor instead.
func (*SwitchTopicResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{23}
}

func (x *SwitchTopicResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *SwitchTopicResponse) GetTopicTitle() string {
	if x != nil {
		return x.TopicTitle
	}
	return ""
}

func (x *SwitchTopicResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SwitchTopicResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// RecallTopicRequest 召回主题请求
type RecallTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TopicQuery    string                 `protobuf:"bytes,2,opt,name=topic_query,json=topicQuery,proto3" json:"topic_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallTopicRequest) Reset() {
	*x = RecallTopicRequest{}
	mi := &file_memory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallTopicRequest) ProtoMessage() {}

func (x *RecallTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallTopicRequest.ProtoReflect.Descriptor instead.
func (*RecallTopicRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{24}
}

func (x *RecallTopicRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecallTopicRequest) GetTopicQuery() string {
	if x != nil {
		return x.TopicQuery
	}
	return ""
}

// RecallTopicResponse 召回主题响应
type RecallTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	TopicTitle    string                 `protobuf:"bytes,2,opt,name=topic_title,json=topicTitle,proto3" json:"topic_title,omitempty"`
	LoadedFromL3  bool                   `protobuf:"varint,3,opt,name=loaded_from_l3,json=loadedFromL3,proto3" json:"loaded_from_l3,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallTopicResponse) Reset() {
	*x = RecallTopicResponse{}
	mi := &file_memory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallTopicResponse) ProtoMessage() {}

func (x *RecallTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallTopicResponse.ProtoReflect.Descriptor instead.
func (*RecallTopicResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{25}
}

func (x *RecallTopicResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *RecallTopicResponse) GetTopicTitle() string {
	if x != nil {
		return x.TopicTitle
	}
	return ""
}

func (x *RecallTopicResponse) GetLoadedFromL3() bool {
	if x != nil {
		return x.LoadedFromL3
	}
	return false
}

func (x *RecallTopicResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// ListTopicsRequest 列出主题请求
type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_memory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{26}
}

func (x *ListTopicsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ListTopicsResponse 列出主题响应
type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicInfo           `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_memory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{27}
}

func (x *ListTopicsResponse) GetTopics() []*TopicInfo {
	if x != nil {
		return x.Topics
	}
	return nil
}

// TopicInfo 主题信息
type TopicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TokenCount    int32                  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt  int64                  `protobuf:"varint,6,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	Tier          string                 `protobuf:"bytes,7,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_memory_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{28}
}

func (x *TopicInfo) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *TopicInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *TopicInfo) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *TopicInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TopicInfo) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

func (x *TopicInfo) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

// GetEntityRelationsRequest 获取实体关系请求
type GetEntityRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRelationsRequest) Reset() {
	*x = GetEntityRelationsRequest{}
	mi := &file_memory_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRelationsRequest) ProtoMessage() {}

func (x *GetEntityRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRelationsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{29}
}

func (x *GetEntityRelationsRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GetEntityRelationsRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// GetEntityRelationsResponse 获取实体关系响应
type GetEntityRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Relations     []*Relation            `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRelationsResponse) Reset() {
	*x = GetEntityRelationsResponse{}
	mi := &file_memory_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRelationsResponse) ProtoMessage() {}

func (x *GetEntityRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetEntityRelationsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{30}
}

func (x *GetEntityRelationsResponse) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GetEntityRelationsResponse) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *GetEntityRelationsResponse) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Relation 关系
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_memory_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{31}
}

func (x *Relation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Relation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Relation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relation) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// SummarizeRequest 摘要请求
type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_memory_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{32}
}

func (x *SummarizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SummaryResponse 摘要响应
type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	MessageCount  int32                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	KeyEntities   []string               `protobuf:"bytes,4,rep,name=key_entities,json=keyEntities,proto3" json:"key_entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_memory_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{33}
}

func (x *SummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummaryResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SummaryResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *SummaryResponse) GetKeyEntities() []string {
	if x != nil {
		return x.KeyEntities
	}
	return nil
}

// ArchiveRequest 归档请求
type ArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TopicTitle    string                 `protobuf:"bytes,2,opt,name=topic_title,json=topicTitle,proto3" json:"topic_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRequest) Reset() {
	*x = ArchiveRequest{}
	mi := &file_memory_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRequest) ProtoMessage() {}

func (x *ArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{34}
}

func (x *ArchiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArchiveRequest) GetTopicTitle() string {
	if x != nil {
		return x.TopicTitle
	}
	return ""
}

// ArchiveResponse 归档响应
type ArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	ArchiveId     string                 `protobuf:"bytes,2,opt,name=archive_id,json=archiveId,proto3" json:"archive_id,omitempty"`
	Archived      bool                   `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResponse) Reset() {
	*x = ArchiveResponse{}
	mi := &file_memory_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResponse) ProtoMessage() {}

func (x *ArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResponse.ProtoReflect.Descriptor instead.
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{35}
}

func (x *ArchiveResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *ArchiveResponse) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *ArchiveResponse) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// GetStatsRequest 获取统计请求
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_memory_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{36}
}

// StatsResponse 统计响应
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1            *TierStats             `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	L2            *TierStats             `protobuf:"bytes,2,opt,name=l2,proto3" json:"l2,omitempty"`
	L3            *TierStats             `protobuf:"bytes,3,opt,name=l3,proto3" json:"l3,omitempty"`
	Total         *TotalStats            `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_memory_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{37}
}

func (x *StatsResponse) GetL1() *TierStats {
	if x != nil {
		return x.L1
	}
	return nil
}

func (x *StatsResponse) GetL2() *TierStats {
	if x != nil {
		return x.L2
	}
	return nil
}

func (x *StatsResponse) GetL3() *TierStats {
	if x != nil {
		return x.L3
	}
	return nil
}

func (x *StatsResponse) GetTotal() *TotalStats {
	if x != nil {
		return x.Total
	}
	return nil
}

// TierStats 层级统计
type TierStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCount  int32                  `protobuf:"varint,1,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	MessageCount  int32                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TokenCount    int64                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierStats) Reset() {
	*x = TierStats{}
	mi := &file_memory_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierStats) ProtoMessage() {}

func (x *TierStats) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierStats.ProtoReflect.Descriptor instead.
func (*TierStats) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{38}
}

func (x *TierStats) GetSessionCount() int32 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

func (x *TierStats) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *TierStats) GetTokenCount() int64 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *TierStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// TotalStats 总计统计
type TotalStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalSessions  int32                  `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	TotalMessages  int32                  `protobuf:"varint,2,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	TotalTokens    int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,4,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TotalStats) Reset() {
	*x = TotalStats{}
	mi := &file_memory_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalStats) ProtoMessage() {}

func (x *TotalStats) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalStats.ProtoReflect.Descriptor instead.
func (*TotalStats) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{39}
}

func (x *TotalStats) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *TotalStats) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *TotalStats) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TotalStats) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

// HealthRequest 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_memory_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{40}
}

// HealthResponse 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_memory_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{41}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\tmemory.v1\"\xab\x02\n" +
	"\fStoreRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x17.memory.v1.MessageInputR\amessage\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.memory.v1.StoreRequest.MetadataEntryR\bmetadata\x121\n" +
	"\aoptions\x18\x05 \x01(\v2\x17.memory.v1.StoreOptionsR\aoptions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\fMessageInput\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\tR\atopicId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x88\x01\n" +
	"\fStoreOptions\x12)\n" +
	"\x10extract_entities\x18\x01 \x01(\bR\x0fextractEntities\x12-\n" +
	"\x12generate_embedding\x18\x02 \x01(\bR\x11generateEmbedding\x12\x1e\n" +
	"\n" +
	"importance\x18\x03 \x01(\x01R\n" +
	"importance\"\xbf\x01\n" +
	"\rStoreResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\x12-\n" +
	"\x12entities_extracted\x18\x04 \x03(\tR\x11entitiesExtracted\x12+\n" +
	"\x11archive_triggered\x18\x05 \x01(\bR\x10archiveTriggered\"|\n" +
	"\x0fRetrieveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x124\n" +
	"\aoptions\x18\x03 \x01(\v2\x1a.memory.v1.RetrieveOptionsR\aoptions\"\xd7\x02\n" +
	"\x0fRetrieveOptions\x12!\n" +
	"\ftoken_budget\x18\x01 \x01(\x05R\vtokenBudget\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x123\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x14.memory.v1.TimeRangeR\ttimeRange\x12A\n" +
	"\afilters\x18\x04 \x03(\v2'.memory.v1.RetrieveOptions.FiltersEntryR\afilters\x12'\n" +
	"\x0finclude_summary\x18\x05 \x01(\bR\x0eincludeSummary\x12)\n" +
	"\x10include_entities\x18\x06 \x01(\bR\x0fincludeEntities\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\xef\x01\n" +
	"\x10RetrieveResponse\x120\n" +
	"\acontext\x18\x01 \x03(\v2\x16.memory.v1.ContextItemR\acontext\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x121\n" +
	"\bentities\x18\x03 \x03(\v2\x15.memory.v1.EntityInfoR\bentities\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x129\n" +
	"\fsearch_stats\x18\x05 \x01(\v2\x16.memory.v1.SearchStatsR\vsearchStats\"\xb5\x01\n" +
	"\vContextItem\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0frelevance_score\x18\x05 \x01(\x01R\x0erelevanceScore\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\tR\x04tier\"P\n" +
	"\n" +
	"EntityInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bmentions\x18\x03 \x01(\x05R\bmentions\"\x84\x01\n" +
	"\vSearchStats\x12\x17\n" +
	"\al1_hits\x18\x01 \x01(\x05R\x06l1Hits\x12\x17\n" +
	"\al2_hits\x18\x02 \x01(\x05R\x06l2Hits\x12\x17\n" +
	"\al3_hits\x18\x03 \x01(\x05R\x06l3Hits\x12*\n" +
	"\x11search_latency_ms\x18\x04 \x01(\x03R\x0fsearchLatencyMs\"\x9f\x01\n" +
	"\x11BatchStoreRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.memory.v1.MessageInputR\bmessages\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.memory.v1.BatchStoreOptionsR\aoptions\"k\n" +
	"\x11BatchStoreOptions\x12%\n" +
	"\x0epreserve_order\x18\x01 \x01(\bR\rpreserveOrder\x12/\n" +
	"\x13parallel_processing\x18\x02 \x01(\bR\x12parallelProcessing\"\xb3\x01\n" +
	"\x12BatchStoreResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.memory.v1.StoreResponseR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\"\x8f\x01\n" +
	"\x14BatchRetrieveRequest\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .memory.v1.SingleRetrieveRequestR\brequests\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.memory.v1.BatchRetrieveOptionsR\aoptions\"L\n" +
	"\x15SingleRetrieveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"Q\n" +
	"\x14BatchRetrieveOptions\x12\x1a\n" +
	"\bparallel\x18\x01 \x01(\bR\bparallel\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"N\n" +
	"\x15BatchRetrieveResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.memory.v1.RetrieveResponseR\aresults\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x82\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\x12\x1f\n" +
	"\vtopic_count\x18\x04 \x01(\x05R\n" +
	"topicCount\x12(\n" +
	"\x10current_topic_id\x18\x05 \x01(\tR\x0ecurrentTopicId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\a \x01(\x03R\flastActiveAt\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"P\n" +
	"\x12SwitchTopicRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tnew_topic\x18\x02 \x01(\tR\bnewTopic\"\x9b\x01\n" +
	"\x13SwitchTopicResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1f\n" +
	"\vtopic_title\x18\x02 \x01(\tR\n" +
	"topicTitle\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x05R\n" +
	"tokenCount\"T\n" +
	"\x12RecallTopicRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtopic_query\x18\x02 \x01(\tR\n" +
	"topicQuery\"\x95\x01\n" +
	"\x13RecallTopicResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1f\n" +
	"\vtopic_title\x18\x02 \x01(\tR\n" +
	"topicTitle\x12$\n" +
	"\x0eloaded_from_l3\x18\x03 \x01(\bR\floadedFromL3\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"2\n" +
	"\x11ListTopicsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"B\n" +
	"\x12ListTopicsResponse\x12,\n" +
	"\x06topics\x18\x01 \x03(\v2\x14.memory.v1.TopicInfoR\x06topics\"\xdb\x01\n" +
	"\tTopicInfo\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\x06 \x01(\x03R\flastActiveAt\x12\x12\n" +
	"\x04tier\x18\a \x01(\tR\x04tier\"R\n" +
	"\x19GetEntityRelationsRequest\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\x86\x01\n" +
	"\x1aGetEntityRelationsResponse\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x121\n" +
	"\trelations\x18\x02 \x03(\v2\x13.memory.v1.RelationR\trelations\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"f\n" +
	"\bRelation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"1\n" +
	"\x10SummarizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x94\x01\n" +
	"\x0fSummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\x12!\n" +
	"\fkey_entities\x18\x04 \x03(\tR\vkeyEntities\"P\n" +
	"\x0eArchiveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtopic_title\x18\x02 \x01(\tR\n" +
	"topicTitle\"k\n" +
	"\x0fArchiveResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1d\n" +
	"\n" +
	"archive_id\x18\x02 \x01(\tR\tarchiveId\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\bR\barchived\"\x11\n" +
	"\x0fGetStatsRequest\"\xae\x01\n" +
	"\rStatsResponse\x12$\n" +
	"\x02l1\x18\x01 \x01(\v2\x14.memory.v1.TierStatsR\x02l1\x12$\n" +
	"\x02l2\x18\x02 \x01(\v2\x14.memory.v1.TierStatsR\x02l2\x12$\n" +
	"\x02l3\x18\x03 \x01(\v2\x14.memory.v1.TierStatsR\x02l3\x12+\n" +
	"\x05total\x18\x04 \x01(\v2\x15.memory.v1.TotalStatsR\x05total\"\x95\x01\n" +
	"\tTierStats\x12#\n" +
	"\rsession_count\x18\x01 \x01(\x05R\fsessionCount\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x03R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\xa7\x01\n" +
	"\n" +
	"TotalStats\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\x05R\rtotalSessions\x12%\n" +
	"\x0etotal_messages\x18\x02 \x01(\x05R\rtotalMessages\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x12(\n" +
	"\x10total_size_bytes\x18\x04 \x01(\x03R\x0etotalSizeBytes\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x9a\b\n" +
	"\rMemoryService\x12:\n" +
	"\x05Store\x12\x17.memory.v1.StoreRequest\x1a\x18.memory.v1.StoreResponse\x12C\n" +
	"\bRetrieve\x12\x1a.memory.v1.RetrieveRequest\x1a\x1b.memory.v1.RetrieveResponse\x12I\n" +
	"\n" +
	"BatchStore\x12\x1c.memory.v1.BatchStoreRequest\x1a\x1d.memory.v1.BatchStoreResponse\x12R\n" +
	"\rBatchRetrieve\x12\x1f.memory.v1.BatchRetrieveRequest\x1a .memory.v1.BatchRetrieveResponse\x12B\n" +
	"\n" +
	"GetSession\x12\x1c.memory.v1.GetSessionRequest\x1a\x16.memory.v1.SessionInfo\x12R\n" +
	"\rDeleteSession\x12\x1f.memory.v1.DeleteSessionRequest\x1a .memory.v1.DeleteSessionResponse\x12L\n" +
	"\vSwitchTopic\x12\x1d.memory.v1.SwitchTopicRequest\x1a\x1e.memory.v1.SwitchTopicResponse\x12L\n" +
	"\vRecallTopic\x12\x1d.memory.v1.RecallTopicRequest\x1a\x1e.memory.v1.RecallTopicResponse\x12I\n" +
	"\n" +
	"ListTopics\x12\x1c.memory.v1.ListTopicsRequest\x1a\x1d.memory.v1.ListTopicsResponse\x12a\n" +
	"\x12GetEntityRelations\x12$.memory.v1.GetEntityRelationsRequest\x1a%.memory.v1.GetEntityRelationsResponse\x12D\n" +
	"\tSummarize\x12\x1b.memory.v1.SummarizeRequest\x1a\x1a.memory.v1.SummaryResponse\x12@\n" +
	"\aArchive\x12\x19.memory.v1.ArchiveRequest\x1a\x1a.memory.v1.ArchiveResponse\x12@\n" +
	"\bGetStats\x12\x1a.memory.v1.GetStatsRequest\x1a\x18.memory.v1.StatsResponse\x12=\n" +
	"\x06Health\x12\x18.memory.v1.HealthRequest\x1a\x19.memory.v1.HealthResponseB:Z8github.com/cloudwego/eino/vdocstool/tools/memory/grpc/pbb\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_memory_proto_goTypes = []any{
	(*StoreRequest)(nil),               // 0: memory.v1.StoreRequest
	(*MessageInput)(nil),               // 1: memory.v1.MessageInput
	(*StoreOptions)(nil),               // 2: memory.v1.StoreOptions
	(*StoreResponse)(nil),              // 3: memory.v1.StoreResponse
	(*RetrieveRequest)(nil),            // 4: memory.v1.RetrieveRequest
	(*RetrieveOptions)(nil),            // 5: memory.v1.RetrieveOptions
	(*TimeRange)(nil),                  // 6: memory.v1.TimeRange
	(*RetrieveResponse)(nil),           // 7: memory.v1.RetrieveResponse
	(*ContextItem)(nil),                // 8: memory.v1.ContextItem
	(*EntityInfo)(nil),                 // 9: memory.v1.EntityInfo
	(*SearchStats)(nil),                // 10: memory.v1.SearchStats
	(*BatchStoreRequest)(nil),          // 11: memory.v1.BatchStoreRequest
	(*BatchStoreOptions)(nil),          // 12: memory.v1.BatchStoreOptions
	(*BatchStoreResponse)(nil),         // 13: memory.v1.BatchStoreResponse
	(*BatchRetrieveRequest)(nil),       // 14: memory.v1.BatchRetrieveRequest
	(*SingleRetrieveRequest)(nil),      // 15: memory.v1.SingleRetrieveRequest
	(*BatchRetrieveOptions)(nil),       // 16: memory.v1.BatchRetrieveOptions
	(*BatchRetrieveResponse)(nil),      // 17: memory.v1.BatchRetrieveResponse
	(*GetSessionRequest)(nil),          // 18: memory.v1.GetSessionRequest
	(*SessionInfo)(nil),                // 19: memory.v1.SessionInfo
	(*DeleteSessionRequest)(nil),       // 20: memory.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),      // 21: memory.v1.DeleteSessionResponse
	(*SwitchTopicRequest)(nil),         // 22: memory.v1.SwitchTopicRequest
	(*SwitchTopicResponse)(nil),        // 23: memory.v1.SwitchTopicResponse
	(*RecallTopicRequest)(nil),         // 24: memory.v1.RecallTopicRequest
	(*RecallTopicResponse)(nil),        // 25: memory.v1.RecallTopicResponse
	(*ListTopicsRequest)(nil),          // 26: memory.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),         // 27: memory.v1.ListTopicsResponse
	(*TopicInfo)(nil),                  // 28: memory.v1.TopicInfo
	(*GetEntityRelationsRequest)(nil),  // 29: memory.v1.GetEntityRelationsRequest
	(*GetEntityRelationsResponse)(nil), // 30: memory.v1.GetEntityRelationsResponse
	(*Relation)(nil),                   // 31: memory.v1.Relation
	(*SummarizeRequest)(nil),           // 32: memory.v1.SummarizeRequest
	(*SummaryResponse)(nil),            // 33: memory.v1.SummaryResponse
	(*ArchiveRequest)(nil),             // 34: memory.v1.ArchiveRequest
	(*ArchiveResponse)(nil),            // 35: memory.v1.ArchiveResponse
	(*GetStatsRequest)(nil),            // 36: memory.v1.GetStatsRequest
	(*StatsResponse)(nil),              // 37: memory.v1.StatsResponse
	(*TierStats)(nil),                  // 38: memory.v1.TierStats
	(*TotalStats)(nil),                 // 39: memory.v1.TotalStats
	(*HealthRequest)(nil),              // 40: memory.v1.HealthRequest
	(*HealthResponse)(nil),             // 41: memory.v1.HealthResponse
	nil,                                // 42: memory.v1.StoreRequest.MetadataEntry
	nil,                                // 43: memory.v1.RetrieveOptions.FiltersEntry
}
var file_memory_proto_depIdxs = []int32{
	1,  // 0: memory.v1.StoreRequest.message:type_name -> memory.v1.MessageInput
	42, // 1: memory.v1.StoreRequest.metadata:type_name -> memory.v1.StoreRequest.MetadataEntry
	2,  // 2: memory.v1.StoreRequest.options:type_name -> memory.v1.StoreOptions
	5,  // 3: memory.v1.RetrieveRequest.options:type_name -> memory.v1.RetrieveOptions
	6,  // 4: memory.v1.RetrieveOptions.time_range:type_name -> memory.v1.TimeRange
	43, // 5: memory.v1.RetrieveOptions.filters:type_name -> memory.v1.RetrieveOptions.FiltersEntry
	8,  // 6: memory.v1.RetrieveResponse.context:type_name -> memory.v1.ContextItem
	9,  // 7: memory.v1.RetrieveResponse.entities:type_name -> memory.v1.EntityInfo
	10, // 8: memory.v1.RetrieveResponse.search_stats:type_name -> memory.v1.SearchStats
	1,  // 9: memory.v1.BatchStoreRequest.messages:type_name -> memory.v1.MessageInput
	12, // 10: memory.v1.BatchStoreRequest.options:type_name -> memory.v1.BatchStoreOptions
	3,  // 11: memory.v1.BatchStoreResponse.results:type_name -> memory.v1.StoreResponse
	15, // 12: memory.v1.BatchRetrieveRequest.requests:type_name -> memory.v1.SingleRetrieveRequest
	16, // 13: memory.v1.BatchRetrieveRequest.options:type_name -> memory.v1.BatchRetrieveOptions
	7,  // 14: memory.v1.BatchRetrieveResponse.results:type_name -> memory.v1.RetrieveResponse
	28, // 15: memory.v1.ListTopicsResponse.topics:type_name -> memory.v1.TopicInfo
	31, // 16: memory.v1.GetEntityRelationsResponse.relations:type_name -> memory.v1.Relation
	38, // 17: memory.v1.StatsResponse.l1:type_name -> memory.v1.TierStats
	38, // 18: memory.v1.StatsResponse.l2:type_name -> memory.v1.TierStats
	38, // 19: memory.v1.StatsResponse.l3:type_name -> memory.v1.TierStats
	39, // 20: memory.v1.StatsResponse.total:type_name -> memory.v1.TotalStats
	0,  // 21: memory.v1.MemoryService.Store:input_type -> memory.v1.StoreRequest
	4,  // 22: memory.v1.MemoryService.Retrieve:input_type -> memory.v1.RetrieveRequest
	11, // 23: memory.v1.MemoryService.BatchStore:input_type -> memory.v1.BatchStoreRequest
	14, // 24: memory.v1.MemoryService.BatchRetrieve:input_type -> memory.v1.BatchRetrieveRequest
	18, // 25: memory.v1.MemoryService.GetSession:input_type -> memory.v1.GetSessionRequest
	20, // 26: memory.v1.MemoryService.DeleteSession:input_type -> memory.v1.DeleteSessionRequest
	22, // 27: memory.v1.MemoryService.SwitchTopic:input_type -> memory.v1.SwitchTopicRequest
	24, // 28: memory.v1.MemoryService.RecallTopic:input_type -> memory.v1.RecallTopicRequest
	26, // 29: memory.v1.MemoryService.ListTopics:input_type -> memory.v1.ListTopicsRequest
	29, // 30: memory.v1.MemoryService.GetEntityRelations:input_type -> memory.v1.GetEntityRelationsRequest
	32, // 31: memory.v1.MemoryService.Summarize:input_type -> memory.v1.SummarizeRequest
	34, // 32: memory.v1.MemoryService.Archive:input_type -> memory.v1.ArchiveRequest
	36, // 33: memory.v1.MemoryService.GetStats:input_type -> memory.v1.GetStatsRequest
	40, // 34: memory.v1.MemoryService.Health:input_type -> memory.v1.HealthRequest
	3,  // 35: memory.v1.MemoryService.Store:output_type -> memory.v1.StoreResponse
	7,  // 36: memory.v1.MemoryService.Retrieve:output_type -> memory.v1.RetrieveResponse
	13, // 37: memory.v1.MemoryService.BatchStore:output_type -> memory.v1.BatchStoreResponse
	17, // 38: memory.v1.MemoryService.BatchRetrieve:output_type -> memory.v1.BatchRetrieveResponse
	19, // 39: memory.v1.MemoryService.GetSession:output_type -> memory.v1.SessionInfo
	21, // 40: memory.v1.MemoryService.DeleteSession:output_type -> memory.v1.DeleteSessionResponse
	23, // 41: memory.v1.MemoryService.SwitchTopic:output_type -> memory.v1.SwitchTopicResponse
	25, // 42: memory.v1.MemoryService.RecallTopic:output_type -> memory.v1.RecallTopicResponse
	27, // 43: memory.v1.MemoryService.ListTopics:output_type -> memory.v1.ListTopicsResponse
	30, // 44: memory.v1.MemoryService.GetEntityRelations:output_type -> memory.v1.GetEntityRelationsResponse
	33, // 45: memory.v1.MemoryService.Summarize:output_type -> memory.v1.SummaryResponse
	35, // 46: memory.v1.MemoryService.Archive:output_type -> memory.v1.ArchiveResponse
	37, // 47: memory.v1.MemoryService.GetStats:output_type -> memory.v1.StatsResponse
	41, // 48: memory.v1.MemoryService.Health:output_type -> memory.v1.HealthResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
