// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: memory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_Store_FullMethodName              = "/memory.v1.MemoryService/Store"
	MemoryService_Retrieve_FullMethodName           = "/memory.v1.MemoryService/Retrieve"
	MemoryService_BatchStore_FullMethodName         = "/memory.v1.MemoryService/BatchStore"
	MemoryService_BatchRetrieve_FullMethodName      = "/memory.v1.MemoryService/BatchRetrieve"
	MemoryService_GetSession_FullMethodName         = "/memory.v1.MemoryService/GetSession"
	MemoryService_DeleteSession_FullMethodName      = "/memory.v1.MemoryService/DeleteSession"
	MemoryService_SwitchTopic_FullMethodName        = "/memory.v1.MemoryService/SwitchTopic"
	MemoryService_RecallTopic_FullMethodName        = "/memory.v1.MemoryService/RecallTopic"
	MemoryService_ListTopics_FullMethodName         = "/memory.v1.MemoryService/ListTopics"
	MemoryService_GetEntityRelations_FullMethodName = "/memory.v1.MemoryService/GetEntityRelations"
	MemoryService_Summarize_FullMethodName          = "/memory.v1.MemoryService/Summarize"
	MemoryService_Archive_FullMethodName            = "/memory.v1.MemoryService/Archive"
	MemoryService_GetStats_FullMethodName           = "/memory.v1.MemoryService/GetStats"
	MemoryService_Health_FullMethodName             = "/memory.v1.MemoryService/Health"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemoryService Memory 服务
type MemoryServiceClient interface {
	// 存储消息
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// 检索上下文
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	// 批量存储
	BatchStore(ctx context.Context, in *BatchStoreRequest, opts ...grpc.CallOption) (*BatchStoreResponse, error)
	// 批量检索
	BatchRetrieve(ctx context.Context, in *BatchRetrieveRequest, opts ...grpc.CallOption) (*BatchRetrieveResponse, error)
	// 获取会话信息
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	// 删除会话
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// 切换主题
	SwitchTopic(ctx context.Context, in *SwitchTopicRequest, opts ...grpc.CallOption) (*SwitchTopicResponse, error)
	// 召回主题
	RecallTopic(ctx context.Context, in *RecallTopicRequest, opts ...grpc.CallOption) (*RecallTopicResponse, error)
	// 列出主题
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	// 获取实体关系
	GetEntityRelations(ctx context.Context, in *GetEntityRelationsRequest, opts ...grpc.CallOption) (*GetEntityRelationsResponse, error)
	// 生成摘要
	Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
	// 归档会话
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
	// 获取统计
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, MemoryService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, MemoryService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) BatchStore(ctx context.Context, in *BatchStoreRequest, opts ...grpc.CallOption) (*BatchStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchStoreResponse)
	err := c.cc.Invoke(ctx, MemoryService_BatchStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) BatchRetrieve(ctx context.Context, in *BatchRetrieveRequest, opts ...grpc.CallOption) (*BatchRetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRetrieveResponse)
	err := c.cc.Invoke(ctx, MemoryService_BatchRetrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, MemoryService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SwitchTopic(ctx context.Context, in *SwitchTopicRequest, opts ...grpc.CallOption) (*SwitchTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchTopicResponse)
	err := c.cc.Invoke(ctx, MemoryService_SwitchTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) RecallTopic(ctx context.Context, in *RecallTopicRequest, opts ...grpc.CallOption) (*RecallTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallTopicResponse)
	err := c.cc.Invoke(ctx, MemoryService_RecallTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetEntityRelations(ctx context.Context, in *GetEntityRelationsRequest, opts ...grpc.CallOption) (*GetEntityRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityRelationsResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetEntityRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, MemoryService_Summarize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, MemoryService_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MemoryService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
//
// MemoryService Memory 服务
type MemoryServiceServer interface {
	// 存储消息
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// 检索上下文
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	// 批量存储
	BatchStore(context.Context, *BatchStoreRequest) (*BatchStoreResponse, error)
	// 批量检索
	BatchRetrieve(context.Context, *BatchRetrieveRequest) (*BatchRetrieveResponse, error)
	// 获取会话信息
	GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error)
	// 删除会话
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// 切换主题
	SwitchTopic(context.Context, *SwitchTopicRequest) (*SwitchTopicResponse, error)
	// 召回主题
	RecallTopic(context.Context, *RecallTopicRequest) (*RecallTopicResponse, error)
	// 列出主题
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	// 获取实体关系
	GetEntityRelations(context.Context, *GetEntityRelationsRequest) (*GetEntityRelationsResponse, error)
	// 生成摘要
	Summarize(context.Context, *SummarizeRequest) (*SummaryResponse, error)
	// 归档会话
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	// 获取统计
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	// 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedMemoryServiceServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedMemoryServiceServer) BatchStore(context.Context, *BatchStoreRequest) (*BatchStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchStore not implemented")
}
func (UnimplementedMemoryServiceServer) BatchRetrieve(context.Context, *BatchRetrieveRequest) (*BatchRetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRetrieve not implemented")
}
func (UnimplementedMemoryServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedMemoryServiceServer) SwitchTopic(context.Context, *SwitchTopicRequest) (*SwitchTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchTopic not implemented")
}
func (UnimplementedMemoryServiceServer) RecallTopic(context.Context, *RecallTopicRequest) (*RecallTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecallTopic not implemented")
}
func (UnimplementedMemoryServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedMemoryServiceServer) GetEntityRelations(context.Context, *GetEntityRelationsRequest) (*GetEntityRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityRelations not implemented")
}
func (UnimplementedMemoryServiceServer) Summarize(context.Context, *SummarizeRequest) (*SummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Summarize not implemented")
}
func (UnimplementedMemoryServiceServer) Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedMemoryServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMemoryServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call panics, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_BatchStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).BatchStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_BatchStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).BatchStore(ctx, req.(*BatchStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_BatchRetrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).BatchRetrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_BatchRetrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).BatchRetrieve(ctx, req.(*BatchRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SwitchTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SwitchTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SwitchTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SwitchTopic(ctx, req.(*SwitchTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_RecallTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).RecallTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_RecallTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).RecallTopic(ctx, req.(*RecallTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetEntityRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetEntityRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetEntityRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetEntityRelations(ctx, req.(*GetEntityRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Summarize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Summarize(ctx, req.(*SummarizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Archive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.v1.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _MemoryService_Store_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _MemoryService_Retrieve_Handler,
		},
		{
			MethodName: "BatchStore",
			Handler:    _MemoryService_BatchStore_Handler,
		},
		{
			MethodName: "BatchRetrieve",
			Handler:    _MemoryService_BatchRetrieve_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _MemoryService_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _MemoryService_DeleteSession_Handler,
		},
		{
			MethodName: "SwitchTopic",
			Handler:    _MemoryService_SwitchTopic_Handler,
		},
		{
			MethodName: "RecallTopic",
			Handler:    _MemoryService_RecallTopic_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _MemoryService_ListTopics_Handler,
		},
		{
			MethodName: "GetEntityRelations",
			Handler:    _MemoryService_GetEntityRelations_Handler,
		},
		{
			MethodName: "Summarize",
			Handler:    _MemoryService_Summarize_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _MemoryService_Archive_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MemoryService_GetStats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MemoryService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory.proto",
}
